apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- sealedsecret.yml
patchesStrategicMerge:
- deployment-patch.yml
images:
- name: cloudflare/cloudflared
  newName: cloudflare/cloudflared
  newTag: 2023.2.1
